(function () {
  'use strict';

  const IMAGE_OUTPUT_PLACEHOLDER_TEXT = [
    '🖼️ この回答は画像出力です。',
    'Recent Viewでは画像本体は表示されません。',
    '通常表示で確認してください。'
  ].join('\n');

  function sanitizeMarkdownText(text) {
    return String(text || '').replace(/\r\n/g, '\n').replace(/\r/g, '\n').trim();
  }

  function buildNonTextMarkdownBody(msg, roleLabel) {
    if (msg?.nonTextResponseType === 'image' || msg?.hasImageLikeContent) {
      return IMAGE_OUTPUT_PLACEHOLDER_TEXT.split('\n').map((line) => `> ${line}`).join('\n');
    }
    return roleLabel === 'user' ? '_No user text message captured._' : '_No assistant text message captured._';
  }

  function renderMarkdownMessageBody(msg, roleLabel) {
    const text = sanitizeMarkdownText(msg?.text || '');
    if (text) return text;
    return buildNonTextMarkdownBody(msg, roleLabel);
  }

  function buildMarkdownHeaderLines({ title, url, conversationId, exportMode, appVersion, generatedAt } = {}) {
    return [
      `# ${sanitizeMarkdownText(title || 'ChatGPT Conversation')}`,
      '',
      `- Source: ${url || ''}`,
      `- Conversation ID: ${conversationId || ''}`,
      `- Export mode: ${exportMode || ''}`,
      `- Generated by: Arcaia ChatGPT Toolkit ${appVersion || ''}`,
      `- Generated at: ${generatedAt || ''}`,
      ''
    ];
  }

  function buildMarkdownTurnHeading(turnIndex, totalTurnCount) {
    if (turnIndex == null) return '## Turn unknown';
    return `## Turn ${Number(turnIndex) + 1}/${totalTurnCount || 1}`;
  }

  function buildMarkdownRoleHeading(roleLabel, index = 0, total = 1) {
    const label = roleLabel || 'Message';
    return Number(total || 0) > 1 ? `### ${label} ${Number(index) + 1}/${total}` : `### ${label}`;
  }

  function getMarkdownMessageSentAt(msg, roleLabel) {
    if (!msg) return '';
    const role = roleLabel || msg.role || '';
    return role === 'assistant'
      ? (msg.update_time_iso || msg.create_time_iso || '')
      : (msg.create_time_iso || msg.update_time_iso || '');
  }

  function buildMarkdownMessageMetadataLines(msg, roleLabel) {
    const sentAt = getMarkdownMessageSentAt(msg, roleLabel);
    return [`- Sent at: ${sentAt || 'unknown'}`];
  }

  function pickMarkdownUserMessages(turn) {
    const userMessages = Array.isArray(turn?.userMessages) ? turn.userMessages : [];
    return userMessages.filter((msg) => msg && (msg.text || msg.nonTextResponseType || msg.hasImageLikeContent));
  }

  function pickFinalAssistantMessageForMarkdown(turn) {
    const assistantMessages = Array.isArray(turn?.assistantMessages) ? turn.assistantMessages : [];
    for (let i = assistantMessages.length - 1; i >= 0; i -= 1) {
      const msg = assistantMessages[i];
      if (!msg) continue;
      if (msg.text || msg.nonTextResponseType || msg.hasImageLikeContent) return msg;
    }
    return assistantMessages[assistantMessages.length - 1] || null;
  }

  window.ArcaiaContentMarkdown = Object.freeze({
    buildMarkdownHeaderLines,
    buildMarkdownTurnHeading,
    buildMarkdownRoleHeading,
    buildMarkdownMessageMetadataLines,
    sanitizeMarkdownText,
    buildNonTextMarkdownBody,
    renderMarkdownMessageBody,
    pickMarkdownUserMessages,
    pickFinalAssistantMessageForMarkdown
  });
})();
